### ISSUE TITLE
Won't receive answers to checkboxes questions 

### ISSUE THREAD

**Issue by Eddy-Burton** [munhozzlucas/SGForms#1]
Hey, first off, thanks for creating this. It's exactly what I was looking for and it works wonderfully 👍

**Context**
I have a form with a checkboxes question. All other questions are being received in Slack except from the answers to the checkboxes question.

**Steps to reproduce**
1. Create Google form
2. Add checkboxes question
3. Save form 
4. Submit form with checkboxes question filled out
5. Slack message will appear but no answer to the checkboxes question will be shown

Apologies for the bad quality images, I'm on a work machine so can't screenshot and export.

![DSC_2244~2.JPG](https://user-images.githubusercontent.com/79575541/233642683-1693ecc8-e6ef-42c6-925e-1f6c2b795fbe.JPG)

![DSC_2245~2.JPG](https://user-images.githubusercontent.com/79575541/233642682-ac99650a-44c1-4aec-9f33-43bb449088de.JPG)

**Comment by munhozzlucas** [comment]
@Eddy-Burton sorry for making you wait so long.

I forgot about those but fixed it. It should work properly now!
